-- ------------------------------
-- database schema initialization
-- ------------------------------

CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ------------------------------
-- 1. users
-- ------------------------------

CREATE TABLE users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email VARCHAR(255) NOT NULL,
                    first_name VARCHAR(50) NOT NULL,
                    last_name VARCHAR(50) NOT NULL,
                    password VARCHAR(255) NOT NULL,
                    role VARCHAR(255),

                    CONSTRAINT uk_users_email UNIQUE (email),
                    CONSTRAINT chk_users_role CHECK (role IN ('PATIENT', 'DOCTOR', 'ADMIN'))
);

-- ------------------------------
-- 2. doctors
-- ------------------------------

CREATE TABLE doctors (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        bio TEXT,
                        experience INTEGER,
                        user_id BIGINT NOT NULL,

                        CONSTRAINT uk_doctors_user UNIQUE (user_id),
                        CONSTRAINT fk_doctors_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ------------------------------
-- 3. specialities
-- ------------------------------

CREATE TABLE specialities (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(255) NOT NULL,
                            code VARCHAR(5),
                            active BOOLEAN NOT NULL DEFAULT TRUE,
                            description VARCHAR(255),

                            CONSTRAINT uk_specialities_code UNIQUE (code),
                            CONSTRAINT uk_specialities_name UNIQUE (name)
);

-- ------------------------------
-- 4. doctor_speciality
-- ------------------------------

CREATE TABLE doctor_speciality (
                                doctor_id BIGINT NOT NULL,
                                speciality_id BIGINT NOT NULL,

                                CONSTRAINT pk_doctor_speciality PRIMARY KEY (doctor_id, speciality_id),
                                CONSTRAINT fk_doctor_speciality_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE CASCADE,
                                CONSTRAINT fk_doctor_speciality_speciality FOREIGN KEY (speciality_id) REFERENCES specialities(id) ON DELETE CASCADE
);

-- ------------------------------
-- 5. time_slots
-- ------------------------------

CREATE TABLE time_slots (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            doctor_id BIGINT NOT NULL,
                            start_time TIMESTAMP WITH TIME ZONE NOT NULL,
                            end_time TIMESTAMP WITH TIME ZONE NOT NULL,
                            version INTEGER NOT NULL DEFAULT 0,

                            CONSTRAINT fk_time_slots_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id) ON DELETE CASCADE,
                            CONSTRAINT no_overlapping_slots EXCLUDE USING gist (
                                                                                    doctor_id WITH =,
                                                                                    tstzrange(start_time, end_time) WITH &&
                                                                                )
);

CREATE INDEX idx_time_slot_doctor_start_time ON time_slots (doctor_id, start_time);

-- ------------------------------
-- 6. appointments
-- ------------------------------

CREATE TABLE appointments (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            status VARCHAR(255) NOT NULL,
                            patient_id BIGINT NOT NULL,
                            time_slot_id BIGINT NOT NULL,

                            CONSTRAINT chk_appointments_status CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELED', 'NO_SHOW')),
                            CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES users(id),
                            CONSTRAINT fk_appointments_time_slot FOREIGN KEY (time_slot_id) REFERENCES time_slots(id)
);

CREATE UNIQUE INDEX idx_appointments_active_time_slot
    ON appointments (time_slot_id)
    WHERE status != 'CANCELED';